name: call-update-digests

on:
  workflow_dispatch:

jobs:
  call:
    permissions:
      contents: write
      pull-requests: write
    uses: runlix/build-workflow/.github/workflows/update-digests-on-call.yml@main
    secrets: inherit

